<style>
    .add {
        border-bottom:1px dotted #627D90;
        padding-bottom:10px;
        height: 10px;
    }

    .button_menu{
        height: 10px;
        padding-top: 10px;
    }
    .button_menu a.menu, .add a.menu{
        padding: 0 10px;
        display: block;
        background-color: #F57912;
        color: #FFF;
        margin-left: 5px;
    }

    .button_menu a.menu {float: right;}

    .add a.menu{float: left;}

    #paging{
        margin-top:20px;
        margin-bottom: 10px;
    }

    #paging a.page{
        border:1px solid #134B7C;
        color:black;width:20px;
        text-align:center;
        background-color:#D9DFE4;
        display:block;float:left;
        margin-right:3px;
        margin-bottom:3px;
        width: 30px;
        padding-top: 2px;
        padding-bottom: 2px;
    }

    #paging .clearer{
        height:10px;
        width:10px;
        float:left;
    }
</style>
<?php if ($this->admin) : ?>
    <div  class="add">
        <a class="menu" href="<?php echo $this->baseUrl . "&show=form&cmd=add" ?>">neuer News-Eintrag</a>
    </div>
<?php endif; ?>

<?php if (!empty($this->data)) : ?>
    <?php foreach ($this->data as $entry) : ?>
        <div class="news_item">
            <?php if ($this->admin) : ?>
                <div class="button_menu">
                    <a class="menu" href="<?php echo $this->baseUrl . "/#" ?>" onclick="if (confirm('Diesen Eintrag wirklich l&ouml;schen ?')) {
                                self.location.href = '<?php echo $this->baseUrl . "&delete=" . $entry["id"] ?>';
                                return false;
                            }" >l&ouml;schen</a>
                    <a class="menu" href="<?php echo $this->baseUrl . "&show=form&cmd=edit&id=" . $entry["id"] ?>">bearbeiten</a>
                </div>
                <?php endif; ?>
            <div style="margin-top:10px;color:#627D90;">
                <?php
                $year = substr($entry['opt2number'], 0, 4);
                $month = substr($entry['opt2number'], 4, 2);
                $day = substr($entry['opt2number'], 6, 2);

                echo $day . '.' . $month . '.' . $year;
                ?>
            </div>

            <h1><?php echo $entry["opt1text"] ?></h1>

            <h2><?php echo $entry["opt2text"] ?></h2>

            <div style="border-bottom:1px dotted #627D90;padding-bottom:10px;">
                <p>
                    <?php
                    if (!empty($entry["opt3text"])) {
                        if ($this->lang == "en") {
                            $more = "more";
                        }
                        else {
                            $more = "mehr";
                        }
                        echo $entry["opt4text"];
                        echo "...[<a class=\"extern\" href=\"" . $entry["opt3text"] . "\">" . $more . "</a>]";
                    }
                    
                    if (!empty($entry["opt1number"])) {
                        if ($this->lang == "en") {
                            $more = "more";
                        }
                        else {
                            $more = "mehr";
                        }
                        echo $entry["opt4text"];
                        echo "...[<a class=\"intern\" href=\"" . $this->baseUrlWithoutIndex . $entry["opt1number"] . "\">" . $more . "</a>]";
                    }
                    
                    if (!empty($entry["opt1clob"])) {
                        $str = "";
                        
                        if ($this->lang == "en") {
                            $more = "more";
                        }
                        else {
                            $more = "mehr";
                        }
                        
                        if (strlen($entry["opt1clob"]) > 250) {
                            $str = substr($entry["opt1clob"], 0, 250);
                        }
                        else {
                            echo $entry["opt1clob"];
                        }
                        echo $str . "...[<a class=\"intern\" href=\"" . $this->baseUrl . "&show=detail&id=" . $entry["id"] . "&np=" . $this->page . "\">" . $more . "</a>]";
                    }
                    ?></p>
            </div>
        </div>
    <?php endforeach; ?>
<?php else : ?>
    <div class="news_item">
        <div class="button_menu">
            <p>keine Eintr&auml;ge vorhanden</p>
        </div>
    </div>
<?php endif; ?>
<div id="paging">
    &nbsp;<?php echo $this->paging ?>
</div>